### ISSUE TITLE
Using n3h with v0.0.4-alpha errors and locks when making first commit

### ISSUE THREAD

**Issue by willemolding** [holochain/n3h#44]
Steps to reproduce:

- Using node version v8.4.0
- Using n3h tag for v0.0.4-alpha
- Using holochain CLI and conductor build form v0.0.4-alpha tagged branch
- Clone this repo (https://github.com/holochain/holochain-basic-chat) DNA and UI are already built using v0.0.4alpha HDK

Running the app using `holochain -c conductor-config.toml` should work fine and using the UI on port 3000 it should be possible to register a user and create a channel

Update the network section of the conductor-config.toml by uncommenting and providing the correct path to n3h repo. Repeating the above steps triggers the following error in holochain when trying to register user using the UI:
```
(@hackmode@) [t] Received IPC:  {"name":"json","data":{"method":"publishEntry","dnaAddress":"QmTi6GA74hkuiyDdvdS4EYbETcHtxsgGQTTsREWeuXy31w","providerAgentId":"sandwich--------------------------------------------------------------------------AAAEqzh28L","address":"QmWkS4r25NSqdT7bSSy9X2XRL9ocgTTpL8MVHRKiwxCCR5","content":{"entry":{"LinkAdd":{"action_kind":"ADD","link":{"base":"sandwich--------------------------------------------------------------------------AAAEqzh28L","target":"Qmb8DamUYDt3n2uLD9qyya7XP9wu4ZfZGir4pof1cmbVaT","tag":"member_of"}}},"header":{"entry_type":"LinkAdd","entry_address":"QmWkS4r25NSqdT7bSSy9X2XRL9ocgTTpL8MVHRKiwxCCR5","provenances":[["sandwich--------------------------------------------------------------------------AAAEqzh28L","TODO"]],"link":"QmTh7DYYFUcdLAqQKpyz19qQQCeo3HnZnbNEjAzTkCzxPS","link_same_type":null,"link_crud":null,"timestamp":"1970-01-01T00:00:00+00:00"}}},"fromZmqId":"006b8b4567"}
(@hackmode@) [t] dhtEntry is known: QmWkS4r25NSqdT7bSSy9X2XRL9ocgTTpL8MVHRKiwxCCR5
(@hackmode@) [t] Received IPC:  {"name":"json","data":{"method":"publishMeta","dnaAddress":"QmTi6GA74hkuiyDdvdS4EYbETcHtxsgGQTTsREWeuXy31w","providerAgentId":"sandwich--------------------------------------------------------------------------AAAEqzh28L","entryAddress":"sandwich--------------------------------------------------------------------------AAAEqzh28L","attribute":"link","contentList":[{"entry":{"LinkAdd":{"action_kind":"ADD","link":{"base":"sandwich--------------------------------------------------------------------------AAAEqzh28L","target":"Qmb8DamUYDt3n2uLD9qyya7XP9wu4ZfZGir4pof1cmbVaT","tag":"member_of"}}},"header":{"entry_type":"LinkAdd","entry_address":"QmWkS4r25NSqdT7bSSy9X2XRL9ocgTTpL8MVHRKiwxCCR5","provenances":[["sandwich--------------------------------------------------------------------------AAAEqzh28L","TODO"]],"link":"QmTh7DYYFUcdLAqQKpyz19qQQCeo3HnZnbNEjAzTkCzxPS","link_same_type":null,"link_crud":null,"timestamp":"1970-01-01T00:00:00+00:00"}}]},"fromZmqId":"006b8b4567"}
2019-02-17 07:21:31:holo-chat: debug/workflow/authoring_entry: QmVsHWNvmeh1Dw26qvfrEoEvh42PSXmDLabM8f2jeRzPst with content: LinkAdd(LinkData { action_kind: ADD, link: Link { base: HashString("Qmb8DamUYDt3n2uLD9qyya7XP9wu4ZfZGir4pof1cmbVaT"), target: HashString("sandwich--------------------------------------------------------------------------AAAEqzh28L"), tag: "has_member" } })
Strict Fail on Unhandled Promise Rejection
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:198:9)
    at getHash (/home/willem/repos/n3h/packages/hackmode/lib/mem.js:16:24)
    at N3hHackMode._metaIdFromTuple (/home/willem/repos/n3h/packages/hackmode/lib/index.js:840:27)
    at N3hHackMode._handleIpcMessage (/home/willem/repos/n3h/packages/hackmode/lib/index.js:233:31)
    at _ipc.on.opt (/home/willem/repos/n3h/packages/hackmode/lib/index.js:80:41)
    at Promise.all._events.(anonymous function).map.fn (/home/willem/repos/n3h/packages/n3h-common/lib/async-class.js:129:14)
    at Array.map (<anonymous>)
    at IpcServer.emit (/home/willem/repos/n3h/packages/n3h-common/lib/async-class.js:128:43)
    at IpcServer._handleMessage (/home/willem/repos/n3h/packages/n3h-ipc/lib/server.js:180:12)
    at exports.Socket._socket.on.args (/home/willem/repos/n3h/packages/n3h-ipc/lib/server.js:39:12)
2019-02-17 07:21:31:holo-chat: debug/workflow/authoring_entry/QmVsHWNvmeh1Dw26qvfrEoEvh42PSXmDLabM8f2jeRzPst: validating...
2019-02-17 07:21:32:holo-chat: Authoring entry QmVsHWNvmeh1Dw26qvfrEoEvh42PSXmDLabM8f2jeRzPst: is valid!
2019-02-17 07:21:32:holo-chat: debug/workflow/authoring_entry/QmVsHWNvmeh1Dw26qvfrEoEvh42PSXmDLabM8f2jeRzPst: committing...
2019-02-17 07:21:32:holo-chat: debug/workflow/authoring_entry/QmVsHWNvmeh1Dw26qvfrEoEvh42PSXmDLabM8f2jeRzPst: committed
2019-02-17 07:21:32:holo-chat: debug/workflow/authoring_entry/QmVsHWNvmeh1Dw26qvfrEoEvh42PSXmDLabM8f2jeRzPst: publishing...
2019-02-17 07:21:32:holo-chat: debug/reduce/link_meta: Publishing link meta for link: Link { base: HashString("Qmb8DamUYDt3n2uLD9qyya7XP9wu4ZfZGir4pof1cmbVaT"), target: HashString("sandwich--------------------------------------------------------------------------AAAEqzh28L"), tag: "has_member" }
2019-02-17 07:21:32:holo-chat: debug/workflow/authoring_entry/QmVsHWNvmeh1Dw26qvfrEoEvh42PSXmDLabM8f2jeRzPst: published!
2019-02-17 07:21:32:holo-chat: debug/workflow/authoring_entry: QmQsXP4eggvKZYZduJQCXWdB8f9Xe5ExX3pPnuHZ3Z739p with content: App(AppEntryType("anchor"), JsonString("\"public_streams\""))
2019-02-17 07:21:32:holo-chat: debug/workflow/authoring_entry/QmQsXP4eggvKZYZduJQCXWdB8f9Xe5ExX3pPnuHZ3Z739p: validating...
2019-02-17 07:21:32:holo-chat: Authoring entry QmQsXP4eggvKZYZduJQCXWdB8f9Xe5ExX3pPnuHZ3Z739p: is valid!
2019-02-17 07:21:32:holo-chat: debug/workflow/authoring_entry/QmQsXP4eggvKZYZduJQCXWdB8f9Xe5ExX3pPnuHZ3Z739p: committing...
2019-02-17 07:21:32:holo-chat: debug/workflow/authoring_entry/QmQsXP4eggvKZYZduJQCXWdB8f9Xe5ExX3pPnuHZ3Z739p: committed
2019-02-17 07:21:32:holo-chat: debug/workflow/authoring_entry/QmQsXP4eggvKZYZduJQCXWdB8f9Xe5ExX3pPnuHZ3Z739p: publishing...
2019-02-17 07:21:32:holo-chat: debug/workflow/authoring_entry/QmQsXP4eggvKZYZduJQCXWdB8f9Xe5ExX3pPnuHZ3Z739p: published!
2019-02-17 07:21:32:holo-chat: debug/workflow/authoring_entry: Qma3hXciK8AWEmZvvjVrmrSBv5Yk4HR2UiBwdZD9PPTKqr with content: LinkAdd(LinkData { action_kind: ADD, link: Link { base: HashString("QmQsXP4eggvKZYZduJQCXWdB8f9Xe5ExX3pPnuHZ3Z739p"), target: HashString("Qmb8DamUYDt3n2uLD9qyya7XP9wu4ZfZGir4pof1cmbVaT"), tag: "public_stream" } })
2019-02-17 07:21:32:holo-chat: debug/workflow/authoring_entry/Qma3hXciK8AWEmZvvjVrmrSBv5Yk4HR2UiBwdZD9PPTKqr: validating...
2019-02-17 07:21:32:holo-chat: Authoring entry Qma3hXciK8AWEmZvvjVrmrSBv5Yk4HR2UiBwdZD9PPTKqr: is valid!
2019-02-17 07:21:32:holo-chat: debug/workflow/authoring_entry/Qma3hXciK8AWEmZvvjVrmrSBv5Yk4HR2UiBwdZD9PPTKqr: committing...
2019-02-17 07:21:32:holo-chat: debug/workflow/authoring_entry/Qma3hXciK8AWEmZvvjVrmrSBv5Yk4HR2UiBwdZD9PPTKqr: committed
2019-02-17 07:21:32:holo-chat: debug/workflow/authoring_entry/Qma3hXciK8AWEmZvvjVrmrSBv5Yk4HR2UiBwdZD9PPTKqr: publishing...
2019-02-17 07:21:32:holo-chat: debug/reduce/link_meta: Publishing link meta for link: Link { base: HashString("QmQsXP4eggvKZYZduJQCXWdB8f9Xe5ExX3pPnuHZ3Z739p"), target: HashString("Qmb8DamUYDt3n2uLD9qyya7XP9wu4ZfZGir4pof1cmbVaT"), tag: "public_stream" }
2019-02-17 07:21:32:holo-chat: debug/workflow/authoring_entry/Qma3hXciK8AWEmZvvjVrmrSBv5Yk4HR2UiBwdZD9PPTKqr: published!
thread '<unnamed>' panicked at 'ErrorMessage { msg: "[puid-1-0] ipc connection timeout" }', net_connection/src/net_connection_thread.rs:83:41
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.




```

The conductor is unresponsive to any further calls.

**Comment by Connoropolous** [comment]
@willemolding I just tested to reproduce. I couldn't. 

I tried nodjes v 11.1.0 and 8.4.0 and both worked. 

When you say you were running `holochain -c conductor-config.toml` does that mean that you downloaded the binary and put it in your path and ran it via the built binary?

**Comment by Connoropolous** [comment]
Sorry I spoke too soon. I can reproduce. I tried different node versions too. P.S. I'm on mac, willems on Linux. 

I tried node 8.4.0, 8.13.0 and 11.10.0 and each resulted in the same error as above.

**Comment by Connoropolous** [comment]
@willemolding did you also see this?
<img width="1012" alt="screen shot 2019-02-16 at 5 37 19 pm" src="https://user-images.githubusercontent.com/1409121/52906022-9c528f80-3211-11e9-99b0-bbd6715b11f3.png">

or is my `zmq` not configured right? (I'm in a Guest user account on my own computer for 'freshness'), but it says it has zmq installed

**Comment by Connoropolous** [comment]
https://github.com/holochain/n3h/blob/7935fb574a06240d1adcd484734d7fc170f7452f/packages/hackmode/lib/mem.js#L16

**Comment by Connoropolous** [comment]
https://github.com/holochain/n3h/blob/a26981e7b7c1893960c499130de77fdf937decd1/packages/hackmode/lib/index.js#L836-L842

**Comment by Connoropolous** [comment]
https://github.com/holochain/n3h/blob/a26981e7b7c1893960c499130de77fdf937decd1/packages/hackmode/lib/index.js#L229-L245

**Comment by Connoropolous** [comment]
https://github.com/holochain/n3h/blob/a26981e7b7c1893960c499130de77fdf937decd1/packages/hackmode/lib/index.js#L80

**Comment by willemolding** [comment]
> @willemolding did you also see this?
> <img alt="screen shot 2019-02-16 at 5 37 19 pm" width="1012" src="https://user-images.githubusercontent.com/1409121/52906022-9c528f80-3211-11e9-99b0-bbd6715b11f3.png">
> 
> or is my `zmq` not configured right? (I'm in a Guest user account on my own computer for 'freshness'), but it says it has zmq installed

Yes I also get that error but further down the page of output. I'll update my post

**Comment by Connoropolous** [comment]
Ok that's important. That's Rust panicking since it didn't get a response, since n3h bailed

**Comment by Connoropolous** [comment]
This code just came in 10 days ago: 
https://github.com/holochain/n3h/commit/7f9ce207fd1926bd6a871e4af464f93999535746#diff-f86a07f89601f94baf850e1d10798f73

**Comment by Connoropolous** [comment]
Cleaned data that triggered the error:
```json
{
  "name": "json",
  "data": {
    "method": "publishMeta",
    "dnaAddress": "QmTi6GA74hkuiyDdvdS4EYbETcHtxsgGQTTsREWeuXy31w",
    "providerAgentId": "sandwich--------------------------------------------------------------------------AAAEqzh28L",
    "entryAddress": "sandwich--------------------------------------------------------------------------AAAEqzh28L",
    "attribute": "link",
    "contentList": [
      {
        "entry": {
          "LinkAdd": {
            "action_kind": "ADD",
            "link": {
              "base": "sandwich--------------------------------------------------------------------------AAAEqzh28L",
              "target": "QmVoUiwYKHQyjSW1uscFaQPqVDP1R6EZVD7mvrn6qX2phb",
              "tag": "member_of"
            }
          }
        },
        "header": {
          "entry_type": "LinkAdd",
          "entry_address": "QmX3Rq8UZknmpBfhR8QR6Q8a9VNhB6bqXnkwXygbYFk6Rn",
          "provenances": [
            [
              "sandwich--------------------------------------------------------------------------AAAEqzh28L",
              "TODO"
            ]
          ],
          "link": "QmRx5FAb5YkJCrWHH27GoMNMaRVX1J7zByCWFbPxrDB5Ua",
          "link_same_type": null,
          "link_crud": null,
          "timestamp": "1970-01-01T00:00:00+00:00"
        }
      }
    ]
  },
  "fromZmqId": "00800041a7"
}
```

**Comment by Connoropolous** [comment]
So then an object like this is being passed as the `metaContent` for the call to `_metaIdFromTuple`
```json
{
        "entry": {
          ...
        },
        "header": {
          ...
        }
  }
```

which is what's causing `getHash` to fail since
"First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object."

**Comment by Connoropolous** [comment]
On the Rust side, it would seem to be related to this comment: 
https://github.com/holochain/holochain-rust/pull/958/files#diff-e4d336e6b388c8569174c921030b5963R17

**Comment by Connoropolous** [comment]
and relatedly this struct, and its `contentList`/`content_list` property
https://github.com/holochain/holochain-rust/blob/a710ecf201bc925886d67e5291b35f22cde5816b/net_connection/src/json_protocol.rs#L204-L220

**Comment by zippy** [comment]
I just set this up and ran it with n3h.  Interestingly on the first node I see  a very different error:
```
Strict Fail on Unhandled Promise Rejection
Error: BUFFER_SHORTAGE
    at DecodeBuffer.reserve (/home/eric/code/metacurrency/holochain/n3h/node_modules/msgpack-lite/lib/flex-buffer.js:64:41)
    at uint8 (/home/eric/code/metacurrency/holochain/n3h/node_modules/msgpack-lite/lib/read-format.js:117:23)
    at Codec.decode (/home/eric/code/metacurrency/holochain/n3h/node_modules/msgpack-lite/lib/read-core.js:22:16)
    at DecodeBuffer.fetch (/home/eric/code/metacurrency/holochain/n3h/node_modules/msgpack-lite/lib/decode-buffer.js:26:21)
    at DecodeBuffer.read (/home/eric/code/metacurrency/holochain/n3h/node_modules/msgpack-lite/lib/flex-buffer.js:166:28)
    at Object.decode (/home/eric/code/metacurrency/holochain/n3h/node_modules/msgpack-lite/lib/decode.js:10:18)
    at LibP2pBundle.send (/home/eric/code/metacurrency/holochain/n3h/packages/n3h-mod-message-libp2p/lib/libp2p-bundle.js:170:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

But on the second node I do see the:
```
Strict Fail on Unhandled Promise Rejection
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
 ```
error

**Comment by zippy** [comment]
That BUFFER_SHORTAGE error seems like a important clue because it's about something incorrect getting passed into message pack some how from n3h.

**Comment by ddd-mtl** [comment]
@zippy I get Error: BUFFER_SHORTAGE messages all the time. They are not the problem

**Comment by ddd-mtl** [comment]
Found the fix:
`_metaIdFromTuple()` was missing this:
`var metaContent = Buffer.from(JSON.stringify(metaContentJson))`

getHash() is expecting a string or Buffer as input, and is receiving a JSON object.
So just needed to do the conversion.

**Comment by Connoropolous** [comment]
it went deeper, there was a bug
https://github.com/holochain/n3h/pull/46/files

**Comment by Connoropolous** [comment]
Pretty sure even after my fixes, there is still an issue with this code:
https://github.com/holochain/n3h/blob/master/packages/hackmode/lib/index.js#L330-L343
Yet to see. Just don't want to forget about it or for it to get dropped
