### ISSUE TITLE
TIMEOUT gossiping with lost peer errors

### ISSUE THREAD

**Issue by Connoropolous** [holochain/n3h#62]
My configuration:
'cloud' node is on a heroku node, running this code:
https://github.com/holochain/n3h/compare/heroku-test

'local' node is on my macbook device, running this code:
https://github.com/holochain/n3h/pull/60/files

Steps to reproduce: 
1. I start the 'cloud' node
2. I copy the P2P binding url, like this:
`wss://172.18.219.118:58022/?a=hkY3_8K5DDoD7on3snTDYrsn7xM1R7lgwTUwTEzUnTUCWk0BDPtCxQaeyMiwAAYWTCwiMBcPTf1Qo9m4tUyzxpR8e0KZE1iZ`
and change it to
`wss://n3hserver.herokuapp.com/?a=hkY3_8K5DDoD7on3snTDYrsn7xM1R7lgwTUwTEzUnTUCWk0BDPtCxQaeyMiwAAYWTCwiMBcPTf1Qo9m4tUyzxpR8e0KZE1iZ`
and add it to local /userdir/.n3h/n3h-config.json under `wssRelayPeers`
3. I run n3h off my device, just by changing dirs to n3h and running `node ./packages/n3h/bin/n3h`
4. After it successfully connects, I wait a bit, then kill the process
5. I check the 'cloud' node and see these logs, and the process dies

```
2019-03-15T21:56:17.215441+00:00 app[web.1]: TIMEOUT gossiping with peer hkb8PBTu8Sa0hmTv078_ikSrcAdmrt0Cvf6xotDWa9WdzMfyWHx6iNJ2YnySLcpYrK58zmCzR5XXENMv_MXlUTlsoBSEkOTZ
2019-03-15T21:56:19.172867+00:00 app[web.1]: Handle Dht Event Error [Object: null prototype] {
2019-03-15T21:56:19.172880+00:00 app[web.1]: type: 'gossipTo',
2019-03-15T21:56:19.172881+00:00 app[web.1]: peerList:
2019-03-15T21:56:19.172883+00:00 app[web.1]: [ 'hkb8PBTu8Sa0hmTv078_ikSrcAdmrt0Cvf6xotDWa9WdzMfyWHx6iNJ2YnySLcpYrK58zmCzR5XXENMv_MXlUTlsoBSEkOTZ' ],
2019-03-15T21:56:19.172884+00:00 app[web.1]: bundle:
2019-03-15T21:56:19.172886+00:00 app[web.1]: 'k6lsb2NIYXNoZXOrdi54dXl2eWNwOHLEQkDbR6BkrUuhJ4l7rY3IrcOf7cQ83gzn9NAcL9+Sj43i1QCRYoXdeRY5nU2H45KCYKsXg56+UfmgKiTahzdBIy1xcw==' } Error: timeout
2019-03-15T21:56:19.172887+00:00 app[web.1]: at Track.track (/app/node_modules/n3h/lib/n3h-common/track.js:74:27)
2019-03-15T21:56:19.172889+00:00 app[web.1]: at P2pBackendHackmodePeer._ensureConnection (/app/node_modules/n3h/lib/hackmode/p2p-backend-hackmode-peer.js:228:39)
2019-03-15T21:56:19.172895+00:00 app[web.1]: at P2pBackendHackmodePeer._ensureCIdForPeerAddress (/app/node_modules/n3h/lib/hackmode/p2p-backend-hackmode-peer.js:251:21)
2019-03-15T21:56:19.183256+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-03-15T21:56:19.183851+00:00 app[web.1]: npm ERR! errno 1
2019-03-15T21:56:19.185572+00:00 app[web.1]: npm ERR! n3hserver@1.0.0 start: `node ./node_modules/n3h/bin/n3h`
2019-03-15T21:56:19.185821+00:00 app[web.1]: npm ERR! Exit status 1
2019-03-15T21:56:19.186220+00:00 app[web.1]: npm ERR!
2019-03-15T21:56:19.186412+00:00 app[web.1]: npm ERR! Failed at the n3hserver@1.0.0 start script.
2019-03-15T21:56:19.186541+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-03-15T21:56:19.191541+00:00 app[web.1]:
2019-03-15T21:56:19.191679+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2019-03-15T21:56:19.191751+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-03-15T21_56_19_187Z-debug.log
2019-03-15T21:56:19.235153+00:00 heroku[web.1]: Process exited with status 1
2019-03-15T21:56:19.250674+00:00 heroku[web.1]: State changed from up to crashed
```

**Comment by Connoropolous** [comment]
This seems to be due to an assumption in the code that states that no connection will drop

**Comment by Connoropolous** [comment]
There is a 'peerHoldRequest' message type which causes the peer to be tracked, but then the `_gossip` call and `_calcState` don't account for the fact that a peer has dropped, they attempt to gossip to/with them anyways. This wouldn't be problematic if it wasn't for the fact that calling
https://github.com/holochain/n3h/blob/ce6eacbf944455b9df503faa12700afdadbaf1bf/lib/n3h-mod-dht-fullsync/dht-fullsync.js#L375-L376
resulted in a timeout which triggers the 'unhandledRejection' because it tries to `_ensureCidConnection` for a peer that's definitely no longer connected

**Comment by Connoropolous** [comment]
Also, why should the whole process exit upon a Dht related error
https://github.com/holochain/n3h/blob/ce6eacbf944455b9df503faa12700afdadbaf1bf/lib/hackmode/p2p-backend-hackmode-peer.js#L89-L92

**Comment by Connoropolous** [comment]
Even if line 91 above is commented out, without the `unhandledRejection.strict()` you will still get a process exit when the timeout happens. 

These timeout errors  should NOT be causing process exits
