### ISSUE TITLE
Two local nodes, one dropping causes error in the remaining

### ISSUE THREAD

**Issue by Connoropolous** [holochain/n3h#66]
Running two local nodes, connected to each, and killing the second one causes this error in the first:

```
Strict Fail on Unhandled Promise Rejection
Error: type check fail (assert.string)
    at K.v (/Users/connor/code/holochain/n3h/lib/n3h-common/type.js:157:17)
    at conError (/Users/connor/code/holochain/n3h/lib/n3h-mod-spec/connection-spec.js:15:17)
    at Object.out.(anonymous function).args [as conError] (/Users/connor/code/holochain/n3h/lib/n3h-common/event.js:52:45)
    at WebSocket.ws.on (/Users/connor/code/holochain/n3h/lib/n3h-mod-connection-wss/wss-connection.js:236:51)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at ClientRequest.req.on (/Users/connor/code/holochain/n3h/node_modules/ws/lib/websocket.js:554:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
Error occured in p2p network module, on tick: TransportError("Os { code: 61, kind: ConnectionRefused, message: \"Connection refused\" }")
```

**Comment by Connoropolous** [comment]
https://github.com/holochain/n3h/blob/ce6eacbf944455b9df503faa12700afdadbaf1bf/lib/n3h-mod-spec/connection-spec.js#L13-L17

this is caused by line 15 which is asserting that `error` is a string, which isn't true, it's an object.

**Comment by Connoropolous** [comment]
Now I am getting this is the log of the actual value of `error`
```
Error: connect ECONNREFUSED 192.168.0.28:60078
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
```
